### ISSUE TITLE
各種DBのデータロード性能の評価

### ISSUE THREAD

**Issue by t2001** [groonga/grnxx#32]
- カラムにインデックスをはった場合とはらない場合のそれぞれを評価

実行環境、使用データは [DB比較実験条件](https://github.com/groonga/grnxx/wiki/DB%E6%AF%94%E8%BC%83%E5%AE%9F%E9%A8%93%E6%9D%A1%E4%BB%B6)

**Comment by t2001** [comment]
これもクローズして大丈夫です。

**Comment by kou** [comment]
わかりました！
